export const GET_USER_ADDRESS_REQUEST = "GET_USER_ADDRESS_REQUEST"
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS"
export const GET_USER_ADDRESS_FAILURE = "GET_USER_ADDRESS_FAILURE"